import { Task } from "./types";

export const tasks: Task[] = [
  {
    id: "task-001",
    title: "Review Q3 Product Roadmap and provide feedback",
    priority: "high",
    status: "pending",
    intent_label: "review_document",
    due_date: "2026-07-06T23:59:00Z",
    source_thread_id: "t-001",
    source_thread_subject: "Q3 Product Roadmap Review — Action Items",
    created_at: "2026-07-04T08:15:00Z",
  },
  {
    id: "task-002",
    title: "Confirm design sprint attendance",
    priority: "high",
    status: "pending",
    intent_label: "schedule_meeting",
    due_date: "2026-07-04T17:00:00Z",
    source_thread_id: "t-003",
    source_thread_subject: "Meeting Tomorrow: Design Sprint Kickoff",
    created_at: "2026-07-04T06:30:00Z",
  },
  {
    id: "task-003",
    title: "Review PR #387 (Search API refactor)",
    priority: "medium",
    status: "pending",
    intent_label: "review_document",
    due_date: "2026-07-05T12:00:00Z",
    source_thread_id: "t-005",
    source_thread_subject: "Can you review this PR? #387",
    created_at: "2026-07-03T15:22:00Z",
  },
  {
    id: "task-004",
    title: "Respond to DataFlow Inc. partnership offer",
    priority: "high",
    status: "pending",
    intent_label: "reply_requested",
    due_date: "2026-07-15T12:00:00Z",
    source_thread_id: "t-007",
    source_thread_subject: "Follow up: Partnership Proposal with DataFlow Inc.",
    created_at: "2026-07-02T14:30:00Z",
  },
  {
    id: "task-005",
    title: "Write handoff notes for vacation",
    priority: "medium",
    status: "pending",
    intent_label: "provide_information",
    due_date: "2026-07-11T17:00:00Z",
    source_thread_id: "t-006",
    source_thread_subject: "Re: Vacation Request Approved",
    created_at: "2026-07-03T10:05:00Z",
  },
  {
    id: "task-006",
    title: "Set up OOO auto-responder",
    priority: "low",
    status: "pending",
    intent_label: "other",
    due_date: "2026-07-13T17:00:00Z",
    source_thread_id: "t-006",
    source_thread_subject: "Re: Vacation Request Approved",
    created_at: "2026-07-03T10:05:00Z",
  },
  {
    id: "task-007",
    title: "Pay SaaS Platform Invoice #4521",
    priority: "low",
    status: "completed",
    intent_label: "make_payment",
    due_date: "2026-07-01T23:59:00Z",
    source_thread_id: "t-002",
    source_thread_subject: "Re: Invoice #4521 — Payment Confirmation",
    created_at: "2026-06-25T09:00:00Z",
  },
  {
    id: "task-008",
    title: "Help backend team with caching layer migration",
    priority: "medium",
    status: "pending",
    intent_label: "provide_information",
    due_date: null,
    source_thread_id: "t-004",
    source_thread_subject: "Weekly Engineering Standup Notes",
    created_at: "2026-07-03T18:00:00Z",
  },
  {
    id: "task-009",
    title: "Follow up on enterprise discount offer",
    priority: "medium",
    status: "dismissed",
    intent_label: "follow_up",
    due_date: "2026-07-20T12:00:00Z",
    source_thread_id: "t-007",
    source_thread_subject: "Follow up: Partnership Proposal with DataFlow Inc.",
    created_at: "2026-07-02T14:30:00Z",
  },
  {
    id: "task-010",
    title: "Check tracking for mechanical keyboard",
    priority: "low",
    status: "completed",
    intent_label: "follow_up",
    due_date: "2026-07-06T12:00:00Z",
    source_thread_id: "t-008",
    source_thread_subject: "Your Amazon order has shipped!",
    created_at: "2026-07-02T09:15:00Z",
  },
];
