import { Task } from "./types";

export const tasks: Task[] = [
  {
    id: "task-001",
    title: "Review Q3 Product Roadmap and provide feedback",
    description: "Sarah Chen requested feedback on the Q3 roadmap covering mobile app v2, API redesign, and ML pipeline budget.",
    priority: "high",
    status: "pending",
    intent_label: "review_document",
    due_date: "2026-07-06T23:59:00Z",
    source_thread_id: "t-001",
    source_thread_subject: "Q3 Product Roadmap Review — Action Items",
    created_at: "2026-07-04T08:15:00Z",
  },
  {
    id: "task-002",
    title: "Confirm design sprint attendance",
    description: "Confirm attendance for the design sprint kickoff tomorrow at 10 AM PST with Marcus Rivera.",
    priority: "high",
    status: "pending",
    intent_label: "schedule_meeting",
    due_date: "2026-07-04T17:00:00Z",
    source_thread_id: "t-003",
    source_thread_subject: "Meeting Tomorrow: Design Sprint Kickoff",
    created_at: "2026-07-04T06:30:00Z",
  },
  {
    id: "task-003",
    title: "Review PR #387 — Search API Refactor",
    description: "Alex Kim requests code review on search API refactor. Includes Elasticsearch query optimization and fuzzy matching.",
    priority: "medium",
    status: "pending",
    intent_label: "review_document",
    due_date: "2026-07-05T18:00:00Z",
    source_thread_id: "t-005",
    source_thread_subject: "Can you review this PR? #387",
    created_at: "2026-07-03T15:22:00Z",
  },
  {
    id: "task-004",
    title: "Reply to DataFlow partnership proposal",
    description: "Emily Zhang is following up on partnership proposal. 20% enterprise discount offer expires July 15th.",
    priority: "high",
    status: "pending",
    intent_label: "reply_requested",
    due_date: "2026-07-15T23:59:00Z",
    source_thread_id: "t-007",
    source_thread_subject: "Follow up: Partnership Proposal with DataFlow Inc.",
    created_at: "2026-07-02T14:30:00Z",
  },
  {
    id: "task-005",
    title: "Prepare vacation handoff notes",
    description: "HR requires handoff notes by July 11 before vacation July 14-18. Set up OOO and delegate urgent items.",
    priority: "medium",
    status: "pending",
    intent_label: "provide_information",
    due_date: "2026-07-11T23:59:00Z",
    source_thread_id: "t-006",
    source_thread_subject: "Re: Vacation Request Approved",
    created_at: "2026-07-03T10:05:00Z",
  },
  {
    id: "task-006",
    title: "Process SaaS platform annual renewal",
    description: "Current plan renews in September. Consider the 15% early renewal discount offered by the billing team.",
    priority: "low",
    status: "pending",
    intent_label: "make_payment",
    due_date: "2026-08-15T23:59:00Z",
    source_thread_id: "t-002",
    source_thread_subject: "Re: Invoice #4521 — Payment Confirmation",
    created_at: "2026-07-04T07:42:00Z",
  },
  {
    id: "task-007",
    title: "Follow up on caching layer migration blocker",
    description: "Engineering standup identified backend team needs help with caching layer migration. Coordinate support.",
    priority: "medium",
    status: "resolved",
    intent_label: "follow_up",
    due_date: "2026-07-05T18:00:00Z",
    source_thread_id: "t-004",
    source_thread_subject: "Weekly Engineering Standup Notes",
    created_at: "2026-07-03T18:00:00Z",
  },
  {
    id: "task-008",
    title: "Reschedule vendor onboarding call",
    description: "Vendor requested rescheduling the onboarding call originally set for July 3rd.",
    priority: "low",
    status: "completed",
    intent_label: "schedule_meeting",
    due_date: "2026-07-03T12:00:00Z",
    source_thread_id: "t-003",
    source_thread_subject: "Meeting Tomorrow: Design Sprint Kickoff",
    created_at: "2026-07-01T09:00:00Z",
  },
  {
    id: "task-009",
    title: "Dismiss newsletter subscription change",
    description: "Automated notification about newsletter frequency change. No action needed.",
    priority: "low",
    status: "dismissed",
    intent_label: "other",
    due_date: null,
    source_thread_id: "t-002",
    source_thread_subject: "Re: Invoice #4521 — Payment Confirmation",
    created_at: "2026-07-02T11:00:00Z",
  },
  {
    id: "task-010",
    title: "Send updated API documentation to client",
    description: "Client requested updated API docs for the v2 endpoints. Compile and send by end of week.",
    priority: "high",
    status: "completed",
    intent_label: "provide_information",
    due_date: "2026-07-04T23:59:00Z",
    source_thread_id: "t-001",
    source_thread_subject: "Q3 Product Roadmap Review — Action Items",
    created_at: "2026-07-02T16:00:00Z",
  },
];
