import { SearchResult, RecentSearch } from "./types";

export const recentSearches: RecentSearch[] = [
  { id: "rs-1", query: "partnership proposal dataflow", timestamp: "2026-07-04T07:00:00Z", result_count: 3 },
  { id: "rs-2", query: "design sprint figma", timestamp: "2026-07-03T15:00:00Z", result_count: 5 },
  { id: "rs-3", query: "invoice payment", timestamp: "2026-07-03T10:00:00Z", result_count: 2 },
  { id: "rs-4", query: "PR review search API", timestamp: "2026-07-02T16:00:00Z", result_count: 4 },
  { id: "rs-5", query: "vacation handoff July", timestamp: "2026-07-02T09:00:00Z", result_count: 1 },
];

export const allSearchResults: SearchResult[] = [
  {
    id: "sr-001",
    type: "thread",
    title: "Follow up: Partnership Proposal with DataFlow Inc.",
    snippet: "Emily Zhang is offering a 20% discount on enterprise tier for a 2-year commitment. Deadline July 15th.",
    relevance_score: 0.95,
    timestamp: "2026-07-02T14:30:00Z",
    metadata: { sender: "Emily Zhang", priority: "high" },
  },
  {
    id: "sr-002",
    type: "task",
    title: "Reply to DataFlow partnership proposal",
    snippet: "Reply requested — Emily Zhang following up on partnership. Discount offer expires July 15th.",
    relevance_score: 0.92,
    timestamp: "2026-07-02T14:30:00Z",
    metadata: { priority: "high", status: "pending" },
  },
  {
    id: "sr-003",
    type: "thread",
    title: "Meeting Tomorrow: Design Sprint Kickoff",
    snippet: "Marcus Rivera confirmed design sprint kickoff for tomorrow 10 AM PST. Sharing Figma files in advance.",
    relevance_score: 0.88,
    timestamp: "2026-07-04T06:30:00Z",
    metadata: { sender: "Marcus Rivera", priority: "high" },
  },
  {
    id: "sr-004",
    type: "thread",
    title: "Q3 Product Roadmap Review — Action Items",
    snippet: "Sarah shared the Q3 product roadmap. Key items include mobile app v2 and API redesign milestones.",
    relevance_score: 0.85,
    timestamp: "2026-07-04T08:15:00Z",
    metadata: { sender: "Sarah Chen", priority: "high" },
  },
  {
    id: "sr-005",
    type: "task",
    title: "Review PR #387 — Search API Refactor",
    snippet: "Alex Kim requests code review on search API refactor with Elasticsearch query optimization.",
    relevance_score: 0.82,
    timestamp: "2026-07-03T15:22:00Z",
    metadata: { priority: "medium", status: "pending" },
  },
  {
    id: "sr-006",
    type: "contact",
    title: "Sarah Chen",
    snippet: "Product Manager at TechCorp — 12 threads, 4 tasks linked. Most recent: Q3 Roadmap Review.",
    relevance_score: 0.78,
    timestamp: "2026-07-04T08:15:00Z",
    metadata: {},
  },
  {
    id: "sr-007",
    type: "thread",
    title: "Re: Invoice #4521 — Payment Confirmation",
    snippet: "Payment of $2,400 confirmed. Next billing cycle August 1st. Annual renewal September.",
    relevance_score: 0.72,
    timestamp: "2026-07-04T07:42:00Z",
    metadata: { sender: "Billing Team", priority: "low" },
  },
  {
    id: "sr-008",
    type: "task",
    title: "Prepare vacation handoff notes",
    snippet: "HR requires handoff notes by July 11 before vacation July 14-18.",
    relevance_score: 0.68,
    timestamp: "2026-07-03T10:05:00Z",
    metadata: { priority: "medium", status: "pending" },
  },
];
