import { Thread, EmailAccount } from "./types";

export const emailAccounts: EmailAccount[] = [
  {
    email: "john.doe@company.com",
    name: "John Doe",
    avatar_color: "#6d5bfa",
    pending_tasks_count: 5,
    provider: "gmail",
  },
  {
    email: "johnd@personal.com",
    name: "John (Personal)",
    avatar_color: "#46d3e5",
    pending_tasks_count: 2,
    provider: "gmail",
  },
];

export const threads: Thread[] = [
  {
    id: "t-001",
    subject: "Q3 Product Roadmap Review — Action Items",
    sender_name: "Sarah Chen",
    sender_email: "sarah.chen@techcorp.io",
    preview: "Hi team, following up on yesterday's meeting. Please review the attached roadmap...",
    summary: "Sarah shared the Q3 product roadmap and requests feedback by Friday. Key items include mobile app v2 launch timeline, API redesign milestones, and budget allocation for the ML pipeline. Three action items assigned to your team.",
    priority: "high",
    workflow_status: "needs_action",
    security_trust_level: "trusted",
    tasks_count: 3,
    timestamp: "2026-07-04T08:15:00Z",
    unread: true,
    message_count: 4,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-002",
    subject: "Re: Invoice #4521 — Payment Confirmation",
    sender_name: "Billing Team",
    sender_email: "billing@saasplatform.com",
    preview: "Your payment of $2,400.00 has been processed successfully...",
    summary: "Payment confirmation for invoice #4521 ($2,400). The next billing cycle starts August 1st. Annual plan renewal is coming up in September — consider the 15% early renewal discount.",
    priority: "low",
    workflow_status: "informational",
    security_trust_level: "neutral",
    tasks_count: 0,
    timestamp: "2026-07-04T07:42:00Z",
    unread: false,
    message_count: 2,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-003",
    subject: "Meeting Tomorrow: Design Sprint Kickoff",
    sender_name: "Marcus Rivera",
    sender_email: "marcus.r@designstudio.co",
    preview: "Hey! Just confirming our design sprint kickoff tomorrow at 10 AM...",
    summary: "Marcus confirmed the design sprint kickoff for tomorrow 10 AM PST. He's sharing Figma files in advance. Expects a 3-day sprint covering user journey mapping, wireframes, and prototype validation.",
    priority: "high",
    workflow_status: "needs_action",
    security_trust_level: "trusted",
    tasks_count: 1,
    timestamp: "2026-07-04T06:30:00Z",
    unread: true,
    message_count: 3,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-004",
    subject: "Weekly Engineering Standup Notes",
    sender_name: "DevOps Bot",
    sender_email: "notifications@devops.internal",
    preview: "Automated summary of this week's engineering standup discussions...",
    summary: "Weekly standup summary: 3 PRs merged, 2 blockers identified (auth service latency, CI pipeline timeout). Sprint velocity is 85% of target. Backend team needs help with the caching layer migration.",
    priority: "medium",
    workflow_status: "informational",
    security_trust_level: "trusted",
    tasks_count: 1,
    timestamp: "2026-07-03T18:00:00Z",
    unread: false,
    message_count: 1,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-005",
    subject: "Can you review this PR? #387",
    sender_name: "Alex Kim",
    sender_email: "alex.kim@company.com",
    preview: "Hey, I've opened PR #387 for the search API refactor. Would appreciate your eyes on it...",
    summary: "Alex requests a code review on PR #387 — search API refactor. Changes include Elasticsearch query optimization, new fuzzy matching logic, and updated test coverage. Estimated review time: 30 minutes.",
    priority: "medium",
    workflow_status: "needs_action",
    security_trust_level: "trusted",
    tasks_count: 1,
    timestamp: "2026-07-03T15:22:00Z",
    unread: true,
    message_count: 2,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-006",
    subject: "Re: Vacation Request Approved",
    sender_name: "HR Department",
    sender_email: "hr@company.com",
    preview: "Your vacation request for July 14-18 has been approved...",
    summary: "Vacation approved for July 14–18. Handoff notes due by July 11. HR reminds to set up OOO auto-responder and delegate urgent matters to your team lead.",
    priority: "low",
    workflow_status: "archived",
    security_trust_level: "trusted",
    tasks_count: 2,
    timestamp: "2026-07-03T10:05:00Z",
    unread: false,
    message_count: 3,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-007",
    subject: "Follow up: Partnership Proposal with DataFlow Inc.",
    sender_name: "Emily Zhang",
    sender_email: "emily@dataflow.io",
    preview: "Hi John, just wanted to follow up on the partnership proposal I sent last week...",
    summary: "Emily is following up on the DataFlow partnership proposal sent last week. She's offering a 20% discount on their enterprise tier for a 2-year commitment. Deadline for the offer is July 15th.",
    priority: "high",
    workflow_status: "follow_up",
    security_trust_level: "unverified",
    tasks_count: 1,
    timestamp: "2026-07-02T14:30:00Z",
    unread: true,
    message_count: 5,
    account_email: "john.doe@company.com",
  },
  {
    id: "t-008",
    subject: "Your Amazon order has shipped!",
    sender_name: "Amazon",
    sender_email: "shipment-tracking@amazon.com",
    preview: "Your order #112-3456789 has been shipped and will arrive by...",
    summary: "Amazon order #112-3456789 shipped. Estimated delivery: July 6th. Contains mechanical keyboard and USB-C hub. Tracking number available in the email.",
    priority: "low",
    workflow_status: "informational",
    security_trust_level: "neutral",
    tasks_count: 0,
    timestamp: "2026-07-02T09:15:00Z",
    unread: false,
    message_count: 1,
    account_email: "johnd@personal.com",
  },
];
