import { SenderProfile } from "./types";

export const senderProfiles: SenderProfile[] = [
  {
    id: "sp-001",
    name: "Sarah Chen",
    email: "sarah.chen@techcorp.io",
    total_emails: 47,
    emails_sent: 22,
    emails_received: 25,
    avg_response_time_hours: 2.3,
    relationship_score: 92,
    last_interaction: "2026-07-04T08:15:00Z",
    top_topics: ["Product Roadmap", "Sprint Planning", "API Design"],
    sentiment: "positive",
  },
  {
    id: "sp-002",
    name: "Marcus Rivera",
    email: "marcus.r@designstudio.co",
    total_emails: 31,
    emails_sent: 14,
    emails_received: 17,
    avg_response_time_hours: 4.1,
    relationship_score: 85,
    last_interaction: "2026-07-04T06:30:00Z",
    top_topics: ["Design Sprint", "UI/UX", "Figma"],
    sentiment: "positive",
  },
  {
    id: "sp-003",
    name: "Alex Kim",
    email: "alex.kim@company.com",
    total_emails: 63,
    emails_sent: 35,
    emails_received: 28,
    avg_response_time_hours: 1.5,
    relationship_score: 95,
    last_interaction: "2026-07-03T15:22:00Z",
    top_topics: ["Code Review", "Backend", "Search API"],
    sentiment: "positive",
  },
  {
    id: "sp-004",
    name: "Emily Zhang",
    email: "emily@dataflow.io",
    total_emails: 12,
    emails_sent: 4,
    emails_received: 8,
    avg_response_time_hours: 18.7,
    relationship_score: 58,
    last_interaction: "2026-07-02T14:30:00Z",
    top_topics: ["Partnership", "Enterprise Pricing", "Integration"],
    sentiment: "neutral",
  },
  {
    id: "sp-005",
    name: "Billing Team",
    email: "billing@saasplatform.com",
    total_emails: 8,
    emails_sent: 1,
    emails_received: 7,
    avg_response_time_hours: 0,
    relationship_score: 30,
    last_interaction: "2026-07-04T07:42:00Z",
    top_topics: ["Invoices", "Payments", "Subscription"],
    sentiment: "neutral",
  },
  {
    id: "sp-006",
    name: "HR Department",
    email: "hr@company.com",
    total_emails: 15,
    emails_sent: 6,
    emails_received: 9,
    avg_response_time_hours: 8.2,
    relationship_score: 45,
    last_interaction: "2026-07-03T10:05:00Z",
    top_topics: ["Vacation", "Policy", "Onboarding"],
    sentiment: "neutral",
  },
];
